baseURL = "https://y.digital/"
defaultContentLanguage = "en"
languageCode = "en-us"
# theme = "ydigital"
title = "Y.digital"
metaDataFormat = "yaml"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true